# Generated by Django 3.0.10 on 2022-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('Number', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
            ],
        ),
    ]
