# Generated by Django 3.0.10 on 2022-08-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Number',
            new_name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Phone',
        ),
    ]
